name: Build and scan a Docker image
on: [push, pull_request, workflow_dispatch]
  
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  POLICY: "chris-wang-se-vulns" # Set the desired Wiz-cli policy to use

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels:  ${{ steps.meta.outputs.labels }}
          load: true
          platforms: linux/arm64

      - name: Download Wiz-cli
        run: curl -o wizcli https://wizcli.app.wiz.io/wizcli && chmod +x wizcli

      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        env:
          WIZ_CLIENT_ID: ${{ vars.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Run wiz-cli docker image scan
        run: ./wizcli docker scan --image  ${{ steps.meta.outputs.tags }} --policy "$POLICY" --output results.sarif,sarif  --dockerfile Dockerfile

      - name: Send image digest to Wiz 
        run: ./wizcli docker tag --image  ${{ steps.meta.outputs.tags }} 


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.sarif
          
      - name: Optional - Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: results.sarif
          category: wiz     


