name: Build and scan a Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  POLICY: "chris-wang-se-vulns" # Set the desired Wiz-cli policy to use

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Download Wiz-cli
        run: curl -o wizcli https://wizcli.app.wiz.io/wizcli && chmod +x wizcli

      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels:  ${{ steps.meta.outputs.labels }}
        # run: docker build . --tag ${{ steps.meta.outputs.tags }}# --label ${{ steps.meta.outputs.labels }}

      - name: Run wiz-cli docker image scan
        run: ./wizcli docker scan --image  ${{ steps.meta.outputs.tags }} --policy "$POLICY"
     
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     